---
title: "p8105_hw5_msk2265"
author: "Mirah"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
```

## Problem 2
```{r}
#making a data frame with all of the file names
file_names = list.files(path = "./data", full.names = TRUE)
```


```{r}
trial= purrr::map(file_names, ~read_csv(.))
  trial = set_names(trial, file_names)
data_df = bind_rows(trial, .id="file_names") # making sure that I can identify the rows of data by adding an id
```


```{r}
#tidying data
data_df = data_df %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "weeks",
    names_prefix = "week_",
    values_to = "measure") %>% 
  mutate(weeks = as.numeric(weeks)) %>% 
  mutate(group = 
           if_else(str_detect(file_names, "con"), "control", "experimental")) %>% 
  mutate(id = match(file_names, unique(file_names))) %>% 
  select(id,everything(), -file_names)
  
           
```
```{r}
#making spaghetti plot:)

ggplot(data = data_df, aes(x = weeks, y= measure, group = id, color=group))+ geom_line()
```

## Problem 3

```{r}
set.seed(1)

#creating function
power = function(mu, n=30, sigma = 5){
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data %>%  
    summarize(
      mu,
      mu_hat = mean(x),
      ttest = broom::tidy(t.test(x, mu=mu, conf.level=.95))
    )
}
```


```{r}
#creating simulations
true_mean_df = c(0,1,2,3,4,5,6)

output_0 = vector("list", 5000)

for (i in 1:5000) {
  output_0[[i]] = power(0)
}
```


```{r}
output_1 = vector("list", 5000)

for (i in 1:5000) {
  output_1[[i]] = power(1)
}
output_2 = vector("list", 5000)

for (i in 1:5000) {
  output_2[[i]] = power(2)
}
output_3 = vector("list", 5000)

for (i in 1:5000) {
  output_3[[i]] = power(3)
}
output_4 = vector("list", 5000)

for (i in 1:5000) {
  output_4[[i]] = power(4)
}
output_5 = vector("list", 5000)

for (i in 1:5000) {
  output_5[[i]] = power(5)
}
output_6 = vector("list", 5000)

for (i in 1:5000) {
  output_6[[i]] = power(6)
}
```


```{r}
sim_results =bind_rows(output_0, output_1, output_2, output_3, output_4, output_5, output_6) %>% 
  mutate(result= ifelse(ttest$p.value<0.05, "reject", "fail to reject")
  )
  
```

```{r}
#plot for power versus true mean
plot1= sim_results %>% 
  group_by(result,mu) %>% 
  count(result, mu) %>% 
  mutate(prop= n/5000) %>% 
  filter(result=="reject") 

  ggplot(plot1, aes(x=mu, y=prop))+geom_point()
  


```

```{r}
plot2= sim_results %>% 
  ungroup() %>% 
  group_by(mu) %>% 
  summarise(avg=mean(mu_hat)) 

ggplot(plot2, aes(x=mu, y=avg))+geom_line()

plot3= sim_results %>% 
  ungroup() %>% 
  group_by(mu) %>% 
  filter(result=="reject") %>% 
  summarise(avg=mean(mu_hat)) 

ggplot(plot3, aes(x=mu, y=avg))+geom_line()
  
```

```

